### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by NickNothom** [DougBarry/powershell-spotify-remove-podcasts#2]
I tried running this in an elevated powershell window and got this error:

```
Unable to back up file xpui.spa
At C:\Users\Nick\Downloads\powershell-spotify-remove-podcasts-main\powershell-spotify-remove-podcasts-main\SpotifyRemovePodcastsEpisodes.ps1:46 char:9
+ catch { throw "Unable to back up file $($SpotifyXPUIdotSPA)" }
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unable to back up file xpui.spa:String) [], RuntimeException
    + FullyQualifiedErrorId : Unable to back up file xpui.spa
 

```
I commented out the backup lines and it runs without any errors, but it doesn't work.

**Comment by DougBarry** [comment]
Hi Nick,

Could you provide me with some more information please:

1. What version of windows are you running? Including if it is Home/Pro/LTSC
2. Did you close Spotify before you ran the script?
3. Did you install Spotify using the official download from their website originally, or through a package manager such as Choco?

Thanks.

**Comment by NickNothom** [comment]
1. Windows 10 Pro
2. Yes
3. Downloaded from the Spotify website. 

It sounds like Spotify made changes very recently

![image](https://user-images.githubusercontent.com/7981005/155197364-df7b5ea6-18ef-45ab-ab6b-f973abf51dca.png)

[Here's the new fix script](https://remysharp.com/downloads/spotify-fix)

**Comment by DougBarry** [comment]
Thanks for the heads up on that. As you can see I've made a change and tested it on my machine here, seems to work. Could you give it a go if you get a chance please? Thanks.

https://github.com/DougBarry/powershell-spotify-remove-podcasts/blob/fix-issue-%232/SpotifyRemovePodcastsEpisodes.ps1

**Comment by DougBarry** [comment]
Closing this issue after testing on a couple of systems and given it some time..  Thanks @NickNothom .
